# Generated by Django 5.0.3 on 2024-04-07 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availabilityID', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availability',
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('activityID', models.AutoField(primary_key=True, serialize=False)),
                ('activityName', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projects')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activity',
            },
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('translationID', models.AutoField(primary_key=True, serialize=False)),
                ('textVolume', models.IntegerField()),
                ('completionPercentage', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.activities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translation',
            },
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('replacementID', models.AutoField(primary_key=True, serialize=False)),
                ('replacementDate', models.DateField()),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.translations')),
            ],
            options={
                'verbose_name': 'Replacement',
                'verbose_name_plural': 'Replacement',
            },
        ),
        migrations.CreateModel(
            name='Mistakes',
            fields=[
                ('mistakeID', models.AutoField(primary_key=True, serialize=False)),
                ('mistakeDescription', models.TextField()),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.translations')),
            ],
            options={
                'verbose_name': 'Mistake',
                'verbose_name_plural': 'Mistake',
            },
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('checkID', models.AutoField(primary_key=True, serialize=False)),
                ('checkResult', models.CharField(max_length=100)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.translations')),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Check',
            },
        ),
    ]
